name: Test

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
        continue-on-error: true
      - run: cat /home/runner/.npm/_logs/*-debug-*.log
        if: failure()
      - run: npm test